version: "3.3"
services:

  proxy:
    image: traefik:v2.4
    container_name: proxy
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.res.acme.tlschallenge=true
      - --certificatesresolvers.res.acme.email=eric.w.burden@gmail.com
      - --certificatesresolvers.res.acme.storage=/letsencrypt/acme.json
    ports:
      - 80:80
      - 443:443
      # - 8080:8080
    networks:
      - ${TRAEFIK_PUBLIC_NETWORK?Variable not set}
      - default
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`dashboard.${DOMAIN?Variable not set}`)
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.tls.certresolver=res
      
      
  shiny:
    image: ericwburden/do-useful-stuff-in-r
    build:
      context: .
      dockerfile: tutorial.dockerfile
    container_name: tutorial
    labels:
      - traefik.enable=true
      - traefik.http.routers.shiny.rule=Host(`${DOMAIN?Variable not set}`)||Host(`www.${DOMAIN?Variable not set}`)
      - traefik.http.routers.shiny.entrypoints=websecure
      - traefik.http.services.shiny.loadbalancer.server.port=3838
      - traefik.http.routers.shiny.tls.certresolver=res
      
networks:
  traefik-public:
    # Allow setting it to false for testing
    external: ${TRAEFIK_PUBLIC_NETWORK_IS_EXTERNAL-true}
